import fs from 'fs';
import path from 'path';
import { pluginManager } from '../src/plugins/index';

function generateReport() {
    const plugins = pluginManager.getFunctionDeclarations();
    
    let report = `<!-- \n🚨 DO NOT EDIT THIS FILE DIRECTLY 🚨 \nThis file is auto-generated by tests/generate_plugin_report.ts. \nAny manual edits will be overwritten.\n-->\n\n`;
    report += `# Legion Ekko Plugin Registry\n\n`;
    report += `Generated on: ${new Date().toISOString()}\n\n`;
    report += `Total Plugins Loaded: **${plugins.length}**\n\n`;
    
    report += `## Plugin Registry\n\n`;
    
    for (const plugin of plugins) {
        report += `### 🔌 ${plugin.name}\n`;
        report += `**Description:** ${plugin.description}\n\n`;
        
        if (plugin.parameters && plugin.parameters.properties) {
            report += `**Parameters:**\n`;
            for (const [paramName, paramData] of Object.entries(plugin.parameters.properties as Record<string, any>)) {
                const isRequired = plugin.parameters.required?.includes(paramName) ? '(Required)' : '(Optional)';
                report += `- \`${paramName}\` [${paramData.type}] ${isRequired}: ${paramData.description || 'No description provided.'}\n`;
            }
            report += '\n';
        } else {
            report += `**Parameters:** None (Takes no arguments)\n\n`;
        }
        report += `---\n\n`;
    }

    const outputPath = path.join(__dirname, '../docs/reports/plugin_registry.md');
    fs.writeFileSync(outputPath, report, 'utf-8');
    console.log(`Report generated successfully at: ${outputPath}`);
}

generateReport();
